config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  defaults format: 'json' do
    resource :point, only: :create
  end

  get 'dashboard', to: 'dashboard#index'
  get 'admin', to: 'admin#index'
  delete 'admin', to: 'admin#destroy', as: 'restart_hackaton'
end

app/models/hackaton.rb
class Hackaton < ActiveRecord::Base
  def award_points(team:, token: '', points: 0, user_name: '', origin: Origin::Slack)
    return unless origin.new(token).valid? && team

    TeamPoint.create(
      team: team,
      value: points,
      user: user_name
    )
  end

  def restart!
    TeamPoint.delete_all
    touch
  end
end

app/models/message.rb
# Public: Represent the message written on slack that triggered the webhook
#
# The Slack outgoing format for the text param is:
#   <botname>: <X> (point|points) to <house_name>...
#
# For more information, consult https://rubyslackapi.slack.com/services/B1RQD447R?added=1
class Message
  POINTS_INDEX = 1
  HOUSE_INDEX = 4

  attr_reader :points, :house_name

  def initialize(message = '')
    @message = message || ''
    @points = parts[POINTS_INDEX].to_i
    @house_name = parts[HOUSE_INDEX]&.capitalize || ''
  end

  def valid?
    points > 0 && house_name.present?
  end

  private

  def parts
    @parts ||= @message.split(' ')
  end
end

app/models/origin/slack.rb
module Origin
  class Slack
    def initialize(token)
      @token = token
    end

    def valid?
      return true unless Rails.env.production?

      @token == token
    end

    private

    def token
      ENV.fetch('SLACK_TOKEN', '')
    end
  end
end

app/models/slack_message.rb
# Public: Represent the message written on slack that triggered the web hook
#
# For more information, consult https://rubyslackapi.slack.com/services/B1RQD447R?added=1
class SlackMessage
  POINTS_INDEX = 0

  attr_reader :points, :team_name, :user_name

  def initialize(message: '', user_name: '')
    @message = message
    @user_name = user_name

    extract_points!
    extract_name!
  end

  def valid?
    points > 0 && !team&.has_member?(@user_name)
  end

  def team
    @team ||= Team.find_by_name(@team_name)
  end

  private

  def extract_points!
    @points = @message.to_s.split(' ')[POINTS_INDEX].to_i
  end

  def extract_name!
    @team_name = /`[^`]+`/.match(@message).to_s.delete('`').capitalize
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :team_points, dependent: :destroy
  has_many :team_aliases, dependent: :destroy
  has_many :team_members, dependent: :destroy

  def points
    team_points.reduce(0) do |sum, team_point|
      sum += team_point.value
    end
  end

  def self.find_by_name(name)
    where('lower(name) = ?', name.downcase).first || find_by_alias(name)
  end

  def has_member?(name)
    team_members.find { |team_member| team_member.name == name }.present?
  end

  private

  def self.find_by_alias(name)
    TeamAlias.where('lower(alias) = ?', name.downcase).first&.team
  end
end

app/models/team_alias.rb
class TeamAlias < ActiveRecord::Base
  belongs_to :team
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  belongs_to :team
end

app/models/team_point.rb
class TeamPoint < ActiveRecord::Base
  belongs_to :team
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: ENV.fetch('ADMIN_USER'),
    password: ENV.fetch('ADMIN_PASSWORD') unless Rails.env.test?

  def index
    @hackaton = hackaton
    @teams = Team.all
    @team_members = TeamMember.all
    @points = TeamPoint.all
    @points_to_audit = points_to_examine
  end

  def destroy
    hackaton.restart!
    redirect_to admin_path
  end

  private

  # TODO: The current hackaton should be found by a url parameter
  def hackaton
    Hackaton.first
  end

  def points_to_examine
    names = @team_members.map(&:name)
    @points.select { |point| names.exclude?(point.user) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @hackaton = Hackaton.first
    @teams = Team.all.sort_by { |team| [-team.points, team.name] }
  end
end

app/controllers/points_controller.rb
class PointsController < ActionController::API
  include ActionController::Helpers
  helper DashboardHelper

  def create
    @hackaton = hackaton

    if slack_message.valid?
      @team = slack_message.team

      @hackaton.award_points(
        team: slack_message.team,
        token: slack_params[:token],
        points: slack_message.points,
        user_name: slack_message.user_name
      )
    end
  end

  private

  def slack_message
    @slack_message ||= SlackMessage.new(
      message: slack_params[:text],
      user_name: slack_params[:user_name]
    )
  end

  # TODO: The current hackaton should be found by a url parameter
  def hackaton
    Hackaton.first
  end

  def slack_params
    params.permit(:token, :team_id, :team_domain, :channel_id, :channel_name,
      :timestamp, :user_id, :user_name, :text, :trigger_word)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  COLORS = [
    'green',
    'pink',
    'blue-grey',
    'purple',
    'red',
    'lime',
    'amber',
    'light-green',
    'orange',
    'brown',
    'deep-orange',
    'teal',
    'indigo',
    'cyan',
    'deep-purple'
  ]

  def card_color(index)
    COLORS[index] || 'green'
  end

  def dashboard_url
    "#{ENV.fetch('SITE_URL')}#{dashboard_path}"
  end
end

app/views/admin/_points.html.erb
<div class="card-panel stats-card">
  <h4 class="header2">Points</h4>

  <ul>
    <% @points_to_audit.each do |p| %>
      <li>
        <%= "#{p.value} point(s) to #{p.team.name} by #{p.user}" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/admin/_reset_panel.html.erb
<div class="card-panel reset-card">
  <h4 class="header2">Reset</h4>
  <div class="row">
    <%= form_tag restart_hackaton_path, method: :delete do %>
      <div class="row">
        <div class="input-field col s12">
          <p>
            If you want to restart the hackaton, click on the red button below. All
            points will be deleted and the game will restart.
          </p>
          <p>
            <b>Caution!</b> this action cannot be undone.
          </p>
          <p>
            Make sure this is what you want, because there is no ressurrection spell
            here, and we did not code checkpoints to which you can return anytime
            you want.
          </p>
        </div>
        <div class="row">
          <div class="input-field col s12">
              <button class="btn red darken-2 waves-effect waves-light right" type="submit" name="action"
                onclick="return confirm('Are you sure?')">Restart Hackaton
                <i class="material-icons left">power_settings_new</i>
              </button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/_stats.html.erb
<div class="card-panel stats-card">
  <h4 class="header2">Stats</h4>
  <ul>
    <li>
      <%= teams_count %> teams
    </li>
    <li>
      <%= team_members_count %> teams members
    </li>
    <li>
      <%= total_points %> points given
    </li>
    <li>
      The game is on since <%= hackaton.created_at.strftime('%d/%m/%Y %H:%M %Z') %>
    </li>
  </ul>
</div>

app/views/admin/index.html.erb
<div class="row">
  <div class="col s12 m12 l4">
    <%= render 'stats', teams_count: @teams.count, total_points: @points.sum(&:value),
      team_members_count: @team_members.count, hackaton: @hackaton %>
  </div>
  <div class="col s12 m12 l4">
    <%= render 'reset_panel' %>
  </div>
  <div class="col s12 m12 l4">
    <%= render 'points' %>
  </div>
</div>

app/views/dashboard/index.html.erb
<section>
  <div class="container">
    <div id="card-stats">
      <div class="row">
        <% @teams.each_with_index do |team, index| %>
          <div class="col s12 m6 l3">
            <div class="card">
              <div class="card-content <%= card_color(index) %> white-text">
                <h1 class="team-avatar">
                  <img src="<%= team.avatar %>" />
                </h1>
                <h2 class="card-stats-number text-center">
                  <%= team.points %>
                </h2>
              </div>
              <div class="card-action <%= card_color(index) %> darken-2">
                <div class="center-align">
                  <%= index + 1 %>. <%= team.name %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="fixed-action-btn horizontal" style="bottom: 45px; right: 24px;">
    <a href="<%= dashboard_path %>" class="btn-floating btn-large teal" title="Reload">
      <i class="large material-icons">replay</i>
    </a>
  </div>
</section>

app/views/layouts/_header.html.erb
<header id="header" class="page-topbar">
  <div class="navbar-fixed">
    <nav class="navbar-color">
      <div class="nav-wrapper">
        <ul class="left">
          <li>
            <h1 class="logo-wrapper">
              <a href="/dashboard" class="brand-logo darken-1">
                <%= @hackaton.present? ? @hackaton.name : 'Hackaton' %>
              </a>
            </h1>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_loader.html.erb
<div id="loader-wrapper">
  <div id="loader"></div>
  <div class="loader-section section-left"></div>
  <div class="loader-section section-right"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackaton Collaboration Bot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <%= render 'layouts/header' %>

    <section>
      <%= yield %>
    </section>

    <%= render 'layouts/loader' %>
  </body>
</html>